"""Local vendor files and offline build: python build_offline.py

Writes vendor/fonts.css and vendor/three-importmap.js, which the labs load instead of Google Fonts and a CDN
(three.js as data: modules, so it also runs from file://), and packs each lab into one self-contained file
in dist/ that makes no network requests (enforced by a Content Security Policy). Downloads are cached in vendor/.
"""
import base64
import json
import re
import sys
import urllib.request
from pathlib import Path

try:  # corporate proxies re-sign TLS; use the OS certificate store if available
    import truststore
    truststore.inject_into_ssl()
except ImportError:
    pass

ROOT = Path(__file__).parent
VENDOR = ROOT / 'vendor'
APPS = {'index.html': 'dist/herzlupe.html', 'klumpfuss/index.html': 'dist/fusslupe.html'}
THREE = 'https://cdn.jsdelivr.net/npm/three@0.186.1/'
FONTSOURCE = 'https://cdn.jsdelivr.net/npm/@fontsource/{pkg}@5/'
MODULES = {  # import specifier -> file in the three package
    'three': 'build/three.module.min.js',
    'three/core': 'build/three.core.min.js',
    'three/addons/controls/OrbitControls.js': 'examples/jsm/controls/OrbitControls.js',
    'three/addons/environments/RoomEnvironment.js': 'examples/jsm/environments/RoomEnvironment.js',
}
FONTS = [('Barlow', 'barlow', w, 'normal') for w in (400, 500, 600)] + [('Barlow', 'barlow', 400, 'italic')]
FONTS += [('Barlow Condensed', 'barlow-condensed', w, 'normal') for w in (500, 600, 700)]
FONTS += [('IBM Plex Mono', 'ibm-plex-mono', w, 'normal') for w in (400, 500)]
SUBSETS = ('latin-ext', 'latin')
CSP = ("default-src 'none'; script-src 'unsafe-inline' data:; worker-src blob:; style-src 'unsafe-inline'; "
       "font-src data:; img-src data:; connect-src 'none'; base-uri 'none'")


def get(url, name):
    path = VENDOR / name
    if not path.exists():
        path.parent.mkdir(parents=True, exist_ok=True)
        req = urllib.request.Request(url, headers={'User-Agent': 'herzlabor-offline-build'})
        with urllib.request.urlopen(req, timeout=60) as r:
            path.write_bytes(r.read())
        print('  downloaded', name)
    return path.read_bytes()


def data_url(mime, raw):
    return f'data:{mime};base64,' + base64.b64encode(raw).decode('ascii')


def replace_once(html, old, new):
    if html.count(old) != 1:
        sys.exit(f'build: expected exactly one occurrence of {old[:60]!r}')
    return html.replace(old, new)


def write_utf8(path, text):
    with path.open('w', encoding='utf-8', newline='\n') as f:
        f.write(text)


def font_css():
    rules = []
    for family, pkg, weight, style in FONTS:
        suffix = '' if style == 'normal' else '-italic'
        css = get(FONTSOURCE.format(pkg=pkg) + f'{weight}{suffix}.css', f'fonts/{pkg}-{weight}{suffix}.css').decode()
        for subset in SUBSETS:
            file = f'{pkg}-{subset}-{weight}-{style}.woff2'
            block = re.search(r'@font-face\s*{[^}]*' + re.escape(file) + r'[^}]*}', css)
            if not block:
                sys.exit(f'build: {file} not found in fontsource css')
            urange = re.search(r'unicode-range:\s*([^;}]+)', block.group(0)).group(1).strip()
            raw = get(FONTSOURCE.format(pkg=pkg) + 'files/' + file, 'fonts/' + file)
            rules.append(f"@font-face{{font-family:'{family}';font-style:{style};font-weight:{weight};font-display:swap;"
                         f"src:url({data_url('font/woff2', raw)}) format('woff2');unicode-range:{urange}}}")
    return '\n'.join(rules)


def import_map():
    imports = {}
    for spec, file in MODULES.items():
        src = get(THREE + file, 'three/' + file).decode('utf-8')
        # data: modules cannot resolve relative imports -> point three.module at the mapped core
        src, n = re.subn(r'''(["'])\./three\.core(?:\.min)?\.js\1''', '"three/core"', src)
        if spec == 'three' and not n:
            sys.exit('build: three.module does not import three.core as expected')
        if re.search(r'''(?:from|import)\s*\(?\s*["']\.{1,2}/''', src):
            sys.exit(f'build: {file} still has relative imports')
        imports[spec] = data_url('text/javascript', src.encode('utf-8'))
    return json.dumps({'imports': imports}, separators=(',', ':'))


def write_local(fonts, imap):
    write_utf8(VENDOR / 'fonts.css', '/* generated by build_offline.py: the lab typefaces as data URLs */\n' + fonts + '\n')
    write_utf8(VENDOR / 'three-importmap.js',
        '// generated by build_offline.py: maps three.js to data: modules before the lab module loads\n'
        "document.currentScript.after(Object.assign(document.createElement('script'), { type: 'importmap', textContent: "
        + json.dumps(imap) + ' }));\n')
    print('vendor/fonts.css, vendor/three-importmap.js written')


def build(src, out, fonts, imap):
    html = (ROOT / src).read_text(encoding='utf-8')
    html = replace_once(html, '<html lang="de">', '<html lang="de" data-build="offline">')
    html = replace_once(html, '<meta charset="utf-8">\n',
                        f'<meta charset="utf-8">\n<meta http-equiv="Content-Security-Policy" content="{CSP}">\n')
    html, n = re.subn(r'<link rel="stylesheet" href="(?:\.\./)?vendor/fonts\.css">', lambda _: f'<style>\n{fonts}\n</style>', html)
    if n != 1:
        sys.exit(f'build: expected the vendor/fonts.css link once in {src}, found {n}')
    html, n = re.subn(r'<script src="(?:\.\./)?vendor/three-importmap\.js"></script>', lambda _: f'<script type="importmap">{imap}</script>', html)
    if n != 1:
        sys.exit(f'build: expected the vendor/three-importmap.js script once in {src}, found {n}')
    resource_html = re.sub(r'<a\b[^>]*>', '', html, flags=re.IGNORECASE)
    remote = re.findall(r'''(?:src\s*=\s*["']https?:|href\s*=\s*["'](?:https?:|(?:\.\./)?vendor/)|url\(\s*["']?https?:|["']https?://[^"']*\.(?:js|css|woff2?)["'])''', resource_html)
    if remote:
        sys.exit(f'build: external resources left in {src}: {remote[:5]}')
    path = ROOT / out
    path.parent.mkdir(exist_ok=True)
    write_utf8(path, html)
    print(f'{out}: {path.stat().st_size / 1e6:.2f} MB')
    if re.search(r"const OWNER = \{[^}]*\b(?:name|street|city|email): ''", html):
        print(f'  note: OWNER in {src} is incomplete, the legal notice still shows placeholders')


def main():
    fonts, imap = font_css(), import_map()
    write_local(fonts, imap)
    for src, out in APPS.items():
        build(src, out, fonts, imap)


if __name__ == '__main__':
    main()
